[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.4"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "=3.2.8"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.2"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.1.0"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "=0.9.3"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "=0.8.1"

[[constraint]]
  name = "github.com/kelseyhightower/memkv"
  version = "0.1.1"

[[constraint]]
  name = "github.com/samuel/go-zookeeper"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "gitlab.com/pastdev/s2i/clconf"

[[override]]
  name = "github.com/ugorji/go"
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"

[[override]]
  name = "google.golang.org/grpc"
  version = "=1.2.1"

[[override]]
  name = "golang.org/x/crypto"
  revision = "1351f936d976c60a0a48d728281922cf63eafb8d"

[[override]]
  name = "golang.org/x/net"
  revision = "c8c74377599bd978aee1cf3b9b63a8634051cec2"

[[override]]
  name = "golang.org/x/sys"
  revision = "e48874b42435b4347fc52bdee0424a52abc974d7"

[[override]]
  name = "github.com/golang/protobuf"
  revision = "4bd1920723d7b7c925de087aa32e2187708897f7"
