name: Integration Tests

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

env:
  GO111MODULE: on
  CONSUL_VERSION: 1.11.2
  ETCD_VERSION: 3.4.3
  VAULT_VERSION: 1.9.3
  DYNAMODB_VERSION: latest
  ZOOKEEPER_VERSION: 3.4.14
  RANCHER_VERSION: 0.6.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: Build and Install
        run: |
          make build
          sudo make install

      - name: Install Dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get install -y curl wget unzip python3-pip make git jq sudo psmisc

      - name: Install Consul
        run: |
          integration/consul/install.sh ${CONSUL_VERSION}

      - name: Test Consul
        run: |
          integration/consul/test.sh
          integration/expect/check.sh

      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '13' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

      - name: Install DynamoDB
        run: |
          integration/dynamodb/install.sh ${DYNAMODB_VERSION}

      - name: Test DynamoDB
        run: |
          integration/dynamodb/test.sh
          integration/expect/check.sh

      - name: Test Env
        run: |
          integration/env/test.sh
          integration/expect/check.sh

      - name: Install etcd
        run: |
          integration/etcd/install.sh ${ETCD_VERSION}

      - name: Test etcd
        run: |
          integration/etcd/test.sh
          integration/expect/check.sh

      - name: Test File
        run: |
          integration/file/test.sh
          integration/expect/check.sh

          #integration/file/test_yaml.sh
          #integration/expect/check.sh
          #integration/file/test_json.sh
          #integration/expect/check.sh

      - name: Install Rancher
        run: |
          integration/rancher/install.sh ${RANCHER_VERSION}

      - name: Test Rancher
        run: |
          integration/rancher/test.sh
          integration/expect/check.sh

      - name: Install Redis
        run: |
          integration/redis/install.sh

      - name: Test Redis
        run: |
          integration/redis/test.sh
          integration/expect/check.sh

      - name: Install Vault
        run: |
          integration/vault/install.sh ${VAULT_VERSION}

      - name: Test Vault V1
        run: |
          integration/vault/v1/test.sh
          integration/expect/check.sh
        env:
          VAULT_ADDR: http://127.0.0.1:8200

      - name: Test Vault Path
        run: |
          integration/vault/v1/test-vaultpath.sh
          integration/expect/check.sh
        env:
          VAULT_ADDR: http://127.0.0.1:8200

      - name: Test Vault Pki
        run: |
          integration/vault/v1/test-vaultpki.sh
          integration/expect/check.sh
        env:
          VAULT_ADDR: http://127.0.0.1:8200

      - name: Test Vault V2
        run: |
          integration/vault/v2/test.sh
          integration/expect/check.sh
        env:
          VAULT_ADDR: http://127.0.0.1:8200

      - name: Install Zookeeper
        run: |
          integration/zookeeper/install.sh ${ZOOKEEPER_VERSION}

      - name: Test Zookeeper
        run: |
          integration/zookeeper/test.sh
          integration/expect/check.sh
